sudo: false

language: haskell

env:
- GHC_VERSION=7.8.4
- GHC_VERSION=7.10.1

install:
- mkdir -p ~/bin
- curl -sL -o - https://github.com/commercialhaskell/stack/releases/download/v0.1.2.0/stack-0.1.2.0-x86_64-linux.gz | zcat > ~/bin/stack
- chmod +x ~/bin/stack
- export PATH=/opt/ghc/$GHC_VERSION/bin:$PATH
- export GHC_OPTIONS="-rtsopts -threaded"
- export STACK="$HOME/bin/stack --stack-yaml stack-$GHC_VERSION.yaml --system-ghc -j2"

script:
- $STACK build --ghc-options "$GHC_OPTIONS"
- $STACK install --ghc-options "$GHC_OPTIONS"
- cp ~/.local/bin/upcast .
- strip -p --strip-unneeded --remove-section=.comment upcast
- upx upcast

cache:
  directories:
  - $HOME/.stack/build-plan-cache
  - $HOME/.stack/snapshots/x86_64-linux/lts-*
  - $HOME/bin

addons:
  apt:
    packages:
    - libgmp3-dev
    - upx-ucl
    - binutils
    - ghc-7.8.4
    - ghc-7.10.1

    sources:
    - hvr-ghc

  artifacts:
    paths:
    - upcast
