sudo: false

language: haskell

env:
- GHC_VERSION=7.10.3

install:
- mkdir -p ~/bin
- curl -sL -o - https://github.com/commercialhaskell/stack/releases/download/v1.0.2/stack-1.0.2-linux-x86_64.tar.gz | tar xfzO - --no-anchored stack > ~/bin/stack
- chmod +x ~/bin/stack
- export PATH=/opt/ghc/$GHC_VERSION/bin:$PATH
- export GHC_OPTIONS="-rtsopts -threaded"
- export STACK="$HOME/bin/stack --system-ghc -j2"

script:
- $STACK build --ghc-options "$GHC_OPTIONS"
- $STACK install --ghc-options "$GHC_OPTIONS"
- cp ~/.local/bin/upcast .
- strip -p --strip-unneeded --remove-section=.comment upcast
- upx upcast

cache:
  directories:
  - $HOME/.stack/build-plan-cache
  - $HOME/.stack/snapshots/x86_64-linux/lts-*
  - $HOME/bin

addons:
  apt:
    packages:
    - libgmp3-dev
    - upx-ucl
    - binutils
    - ghc-7.10.3

    sources:
    - hvr-ghc

  artifacts:
    paths:
    - upcast
